accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('register/', views.register, name='register'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.dashboard, name='dashboard'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
]

cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout')
]

e-shop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),

    path('__reload__/', include('django_browser_reload.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class MyAccountManager(BaseUserManager):
      '''
      Custom user manager for creating and managing user accounts.
      '''
      def create_user(self, first_name, last_name, username, email, password=None):
            if not email:
                  raise ValueError('Email required')

            if not username:
                  raise ValueError('Username required')

            user = self.model(
                  email      = self.normalize_email(email),
                  username   = username,
                  first_name = first_name,
                  last_name  = last_name,
            )

            user.set_password(password)
            user.save(using=self._db)
            return user

      def create_superuser(self, first_name, last_name, email, username, password):
            user = self.create_user(
                  email      = self.normalize_email(email),
                  username   = username,
                  password   = password,
                  first_name = first_name,
                  last_name  = last_name,
            )
            user.is_admin      = True
            user.is_active     = True
            user.is_staff      = True
            user.is_superadmin = True
            user.save(using=self._db)
            return user


class Account(AbstractBaseUser):
      '''
      Custom user model for user accounts.
      '''
      first_name   = models.CharField(max_length=50)
      last_name    = models.CharField(max_length=50)
      username     = models.CharField(max_length=50, unique=True)
      email        = models.EmailField(max_length=100, unique=True)
      phone_number = models.CharField(max_length=50)

      # Required
      date_joined   = models.DateTimeField(auto_now_add=True)
      last_login    = models.DateTimeField(auto_now_add=True)
      is_admin      = models.BooleanField(default=False)
      is_staff      = models.BooleanField(default=False)
      is_active     = models.BooleanField(default=False)
      is_superadmin = models.BooleanField(default=False)

      # Login with email
      USERNAME_FIELD  = 'email'
      REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

      objects = MyAccountManager()

      def full_name(self):
            return f'{self.first_name} {self.last_name}'

      def __str__(self):
            return self.email

      def has_perm(self, perm, obj=None):
            return self.is_admin

      def has_module_perms(self, add_label):
            return True


class UserProfile(models.Model):
    """
    Model for storing additional user profile information.
    """
    user            = models.OneToOneField(Account, on_delete=models.CASCADE)
    address_line_1  = models.CharField(blank=True, max_length=100)
    address_line_2  = models.CharField(blank=True, max_length=100)
    profile_picture = models.ImageField(
        upload_to='userprofile/',
        default='userprofile/default-profile.png',
        blank=True,
        null=True
    )
    city    = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)

    def __str__(self):
        return self.user.first_name

    def full_address(self):
        """
        Returns the full address of the user.
        """
        return f'{self.address_line_1}, {self.address_line_2}, {self.city}, {self.country}'

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RegistrationForm, UserForm, UserProfileForm
from .models import Account, UserProfile
from orders.models import Order, OrderProduct
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from cart.views import _cart_id
from cart.models import Cart, CartItem

import requests


def register(request):
    '''
    Handles user registration by processing the submitted form, creating a user account,
    and sending an email verification link.
    '''
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name        = form.cleaned_data['first_name']
            last_name         = form.cleaned_data['last_name']
            phone_number      = form.cleaned_data['phone_number']
            email             = form.cleaned_data['email']
            password          = form.cleaned_data['password']
            username          = email.split("@")[0]
            user              = Account.objects.create_user(first_name=first_name, last_name=last_name, email=email, username            = username, password=password)
            user.phone_number = phone_number
            user.save()

            # Create a user profile
            profile                 = UserProfile()
            profile.user_id         = user.id
            profile.profile_picture = 'default/default-user.png'
            profile.save()

            # USER ACTIVATION
            current_site    = get_current_site(request)
            mail_subject    = 'iShop - Activation'
            message         = render_to_string('accounts/account_verification_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email    = email
            send_email  = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()
            return redirect('/accounts/login/?command=verification&email='+email)
    else:
        form    = RegistrationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/register.html', context)


def signin(request):
    '''
    Handles user sign-in by authenticating the provided email and password,
    and manages the user's cart items upon successful login.
    '''
    if request.method == "POST":
        email    = request.POST['email']
        password = request.POST['password']
        user     = auth.authenticate(email=email, password=password)

        if user is not None:
            try:
                cart                = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)

                    # Product variation > Cart Id
                    product_variation = []
                    for item in cart_item:
                        variation = item.variations.all()
                        product_variation.append(list(variation))

                    # Cart Items > User > Product Variations
                    cart_item   = CartItem.objects.filter(user=user)
                    ex_var_list = []
                    id          = []
                    for item in cart_item:
                        existing_variation = item.variations.all()
                        ex_var_list.append(list(existing_variation))
                        id.append(item.id)

                    for pr in product_variation:
                        if pr in ex_var_list:
                            index          = ex_var_list.index(pr)
                            item_id        = id[index]
                            item           = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user      = user
                            item.save()
                        else:
                            cart_item = CartItem.objects.filter(cart=cart)
                            for item in cart_item:
                                item.user = user
                                item.save()
            except:
                pass
            auth.login(request, user)
            messages.success(request, 'Login Successfull!')
            url = request.META.get('HTTP_REFERER')
            try:
                query  = requests.utils.urlparse(url).query
                params = dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    nextPage = params['next']
                    return redirect('nextPage')
            except:
                return redirect('dashboard')
        else:
            messages.error(request, 'Invalid Login Credentials.')
            return redirect('signin')
    return render(request, 'accounts/signin.html')


@login_required(login_url = 'signin')
def signout(request):

    auth.logout(request)
    messages.success(request, 'Loggout Successful!')
    return redirect('signin')


def activate(request, uidb64, token):
    """
    Logs out the user and redirects them to the sign-in page.
    """
    try:
        uid  = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Account is activated!')
        return redirect('signin')
    else:
        messages.error(request, 'invalid activation link')
    return redirect('register')


@login_required(login_url='signin')
def dashboard(request):
    '''
    Dashboard view for user profile and orders.
    '''
    orders       = Order.objects.filter(user_id=request.user.id, is_ordered=True).order_by('-created_at')
    orders_count = orders.count()

    # Safe query - Guaranteed UserProfile exists.
    userprofile = UserProfile.objects.get(user=request.user)

    context = {
        'orders_count': orders_count,
        'userprofile' : userprofile,
    }
    return render(request, 'accounts/dashboard.html', context)


def reset_password(request):
    '''
    This view handles the password reset process. It expects a POST request
    containing the new password and its confirmation. If the passwords match,
    it retrieves the user ID from the session, fetches the corresponding user
    object, updates the password, and saves the changes. A success message is
    displayed, and the user is redirected to the sign-in page. If the passwords
    do not match, an error message is displayed, and the user is redirected back
    to the password reset page.
    '''
    if request.method == 'POST':
        password         = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid  = request.session.get('uid')
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Password reset successful')
            return redirect('signin')
        else:
            messages.error(request, 'Password do not match!')
            return redirect('reset_password')
    else:
        return render(request, 'accounts/reset_password.html')


@login_required(login_url='signin')
def my_orders(request):
    '''
    This view retrieves orders associated with the authenticated user that are marked as completed.
    The orders are sorted by the creation date in descending order.
    The list of orders is passed to the template for rendering.
    '''
    orders  = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
    context = {
        'orders': orders,
    }
    return render(request, 'accounts/my_orders.html', context)


@login_required(login_url='signin')
def edit_profile(request):
    '''
    This view handles the GET and POST requests for editing the user profile.
    If the request method is POST and both the user form and profile form are valid,
    it saves the changes and redirects the user to the edit profile page with a success message.
    If there are any errors, appropriate error messages are displayed.
    '''
    userprofile = get_object_or_404(UserProfile, user=request.user)
    if request.method == 'POST':
        user_form    = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

            messages.success(request, 'Your Profile has been updated!')
            return redirect('edit_profile')
    else:
        user_form    = UserForm(instance=request.user)
        profile_form = UserProfileForm(instance=userprofile)

    context = {
        'user_form'   : user_form,
        'profile_form': profile_form,
        'userprofile' : userprofile,
    }
    return render(request, 'accounts/edit_profile.html', context)


@login_required(login_url='signin')
def change_password(request):
    '''
    This view handles the POST request for changing the password. It verifies the current password,

templates/accounts/account_verification_email.html
{% autoescape off %}
    <div style="text-align: center;">
        Welcome <strong>{{ user.first_name }}</strong>!
        <br><br>
        To activate your account, click
        <a href="http://{{ domain }}{% url 'activate' uidb64=uid token=token %}"
            target="_blank" rel="noopener noreferrer">here
        </a>
    </div>
{% endautoescape %}

templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block title %} E-SHOP @ Change Password {% endblock %}

{% block content %}
<section>
    <!-- ALERT MESSAGES -->
    {% include 'includes/alerts.html' %}
    <div class="container dash-container">
        <div class="row">
            <!-- DASHBOARD_SIDEBAR.HTML -->
            {% include 'includes/dashboard_sidebar.html' %}
            <!-- DASHBOARD.HTML -->
            <main class="col-md-9">
                <article class="card dashboard-card d-card">
                    <div class="dash-header-container">
                        <div class="dash-header">CHANGE PASSWORD: {{user.full_name}}</div>
                    </div>
                    <div class="card-body">
                        <form class="change-form" action="{% url 'change_password' %}" method="POST">
                            {% csrf_token %}
                            <!-- Current Password -->
                            <div class="form-group"><label>Current Password:</label>
                                <input type="password" name="current_password" placeholder="Current Password" class="form-control" required>
                                {{ profile_form.address_line_1 }}
                            </div>
                            <!-- New Password -->
                            <div class="form-group"><label>New Password:</label>
                                <input type="password" name="new_password" placeholder="New Password" class="form-control" required>
                            </div>
                            <!-- Confirm Password -->
                            <div class="form-group"><label>Confirm Password:</label>
                                <input type="password" name="confirm_new_password" placeholder="Confirm New Password" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <div class="btn-container text-center">
                                    <input type="submit" value="SUBMIT" class="btn">
                                </div>
                            </div>
                        </form>
                    </div>
                </article>
            </main>
        </div>
    </div>
</section>
{% endblock %}

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Dashboard - {{ user.full_name }} | E-SHOP{% endblock %}

{% block content %}
<section>

    {% include 'includes/alerts.html' %}
    <div class="container dash-container">
        <div class="row">

            {% include 'includes/dashboard_sidebar.html' %}

            <main class="col-md-9">
                <article class="card dashboard-card">
                    <div class="dash-header-container">
                        <div class="dash-header">DASHBOARD: {{user.full_name}}</div>
                    </div>

                    <!-- Sticks 2 cards in dashboard together -->
                    <div class="dash-row">

                        <!-- Profile Info with Fallback -->
                        <div class="col-6">
                            <div class="card">
                                <div class="dash-card-body">
                                    {% if userprofile.profile_picture %}
                                        <img class="dash-img" src="{{ userprofile.profile_picture.url }}" alt="User Profile Picture">
                                    {% else %}
                                        <img class="dash-img" src="/media/userprofile/default-profile.png" alt="Default Profile Image">
                                    {% endif %}
                                    <div class="dash-user-info">{{ user.full_name }}</div>
                                    <div class="dash-user-info">{{ user.email }}</div>
                                    <div class="dash-user-info">{{ user.phone_number }}</div>
                                </div>
                            </div>
                        </div>

                        <!-- Orders Information -->
                        <div class="col-6">
                            <div class="card">
                                <div class="dash-card-body">
                                    <div class="semi-bold">Total Orders:</div>
                                    <div class="semi-bold">{{ orders_count }}</div>
                                    <a class="cart-link" href="{% url 'my_orders' %}">Order History</a>
                                </div>
                            </div>
                        </div>
                    </div>

                </article>
            </main>
        </div>
    </div>
</section>
{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %} E-SHOP @ Edit Profile {% endblock %}

{% block content %}
<section>

    <!-- ALERT MESSAGES -->
    {% include 'includes/alerts.html' %}
    <div class="container dash-container">
        <div class="row">

            <!-- DASHBOARD_SIDEBAR.HTML -->
            {% include 'includes/dashboard_sidebar.html' %}


            <main class="col-md-9">
                <article class="card dashboard-card d-card">
                    <div class="dash-header-container">
                        <div class="dash-header">Edit Profle: {{user.full_name}}</div>
                    </div>
                    <div class="card-body">
                        <form class="edit-form" action="{% url 'edit_profile' %}"method="POST"enctype="multipart/form-data">
                            {% csrf_token %}

                            <!-- USER PROFILE PICTURE -->
                            <div class="form-row">
                                <div class="form-group">
                                    {% if userprofile.profile_picture and userprofile.profile_picture.url %}
                                        <img class="edit-profile-picture" src="{{ userprofile.profile_picture.url }}" alt="User Profile Picture">
                                    {% else %}
                                        <img class="edit-profile-picture" src="{% static 'images/misc/default_profile.png' %}" alt="Default Profile Picture">
                                    {% endif %}
                                </div>
                            </div>

                            <!-- Upload Profile Picture -->
                            <div class="form-row">
                                <div class="form-group edit-form-picture">
                                    <label class="edit-label-picture" for="id_profile_picture">Profile Picture:</label>
                                    {{ profile_form.profile_picture }}
                                </div>
                            </div>

                            <!-- First & Last Name -->
                            <div class="form-row">
                                <div class="form-group"><label for="id_first_name">First Name:</label>
                                    {{ user_form.first_name }}
                                </div>
                                <div class="form-group">
                                    <label for="id_last_name">Last Name:</label>
                                    {{ user_form.last_name }}
                                </div>
                            </div>

                            <!-- Phone Number -->
                            <div class="form-row">
                                <div class="form-group"><label for="id_phone_number">Phone number:</label>
                                    {{ user_form.phone_number }}
                                </div>
                            </div>

                            <!-- Address 1 & 2 -->
                            <div class="form-row">
                                <div class="form-group"><label for="id_address_line_1">Address 1:</label>
                                    {{ profile_form.address_line_1 }}
                                </div>
                                <div class="form-group"><label for="id_address_line_2">Address 2:</label>
                                    {{ profile_form.address_line_2 }}
                                </div>
                            </div>

                            <!-- City & Country -->
                            <div class="form-row">
                                <div class="form-group"><label for="id_city">City:</label>
                                    {{ profile_form.city }}
                                </div>
                                <div class="form-group"><label for="id_country">Country:</label>
                                    {{ profile_form.country }}
                                </div>
                            </div>

                            <!-- Submit Button -->
                            <div class="form-row">
                                <div class="form-group">
                                    <div class="btn-container text-center">
                                        <input type="submit" value="UPDATE" class="btn">
                                    </div>
                                </div>
                            </div>

                        </form>
                    </div>
                </article>
            </main>
        </div>
    </div>
</section>
{% endblock %}

templates/accounts/my_orders.html
{% extends 'base.html' %}
{% load static %}

{% block title %} E-SHOP @ My Orders {% endblock %}

{% block content %}
<section>
    <!-- ALERT MESSAGES -->
    {% include 'includes/alerts.html' %}
    <div class="container dash-container">
        <div class="row">
            <!-- DASHBOARD_SIDEBAR.HTML -->
            {% include 'includes/dashboard_sidebar.html' %}
            <!-- DASHBOARD.HTML -->
            <main class="col-md-9">
                <article class="card dashboard-card">
                    <div class="dash-header-container">
                        <div class="dash-header">Order History: {{user.full_name}}</div>
                    </div>
                    <!-- Order History Table -->
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th class="myorders-text">Order #</th>
                                            <th class="myorders-text">Billing Name:</th>
                                            <th class="myorders-text">Phone Number:</th>
                                            <th class="myorders-text">Order Total:</th>
                                            <th class="myorders-text">Date:</th>
                                        </tr>
                                    </thead>
                                    {% if orders %}
                                        <tbody>
                                        {% for order in orders %}
                                            <tr>
                                                <td scope="row">
                                                    <a class="myorders-text" href="{% url 'order_detail' order.order_number %}">
                                                        {{order.order_number}}
                                                    </a>
                                                </td>
                                                <td class="myorders-text">{{order.full_name}}</td>
                                                <td class="myorders-text">{{order.phone}}</td>
                                                <td class="myorders-text">${{order.order_total}}</td>
                                                <td class="myorders-text">{{order.created_at}}</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                        {% else %}
                                        <tbody>
                                            <tr>
                                                <td class="myorders-td" colspan="5">No orders found</td>
                                            </tr>
                                        </tbody>
                                    {% endif %}
                                </table>
                            </div>
                        </div>
                    </div>
                </article>
            </main>
        </div>
    </div>
</section>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %} E-SHOP @ Register {% endblock %}

{% block content %}
    <section class="content-down">
        <div class="card-width-400">
            <article class="card-body">
                {% include 'includes/alerts.html' %}
                <h2 class="form-header">REGISTER:</h2>
                <form action="{% url 'register' %}" method="POST">
                    {% csrf_token %}

                    <!-- First & Last Name -->
                    <div class="form-row">
                        <div class="col form-group">
                            <label>First Name:</label>
                            {{ form.first_name }}
                        </div>
                        <div class="col form-group">
                            <label>Last Name:</label>
                            {{ form.last_name }}
                        </div>
                    </div>

                    <!-- Email & Phone -->
                    <div class="form-row">
                        <div class="col form-group">
                            <label>Email:</label>
                            {{ form.email }}
                        </div>
                        <div class="col form-group">
                            <label>Phone Number:</label>
                            {{ form.phone_number }}
                        </div>
                    </div>

                    <!-- Create & Confirm Password -->
                    <div class="form-row">
                        <div class="col form-group">
                            <label>Create a Password:</label>
                            {{ form.password }}
                        </div>
                        <div class="col form-group">
                            <label>Confirm the Password:</label>
                            {{ form.confirm_password }}
                        </div>
                    </div>

                    <!-- Submit Button -->
                    <div class="form-row">
                        <div class="col form-group">
                            <div class="btn-container">
                                <button type="submit" class="btn">REGISTER</button>
                            </div>
                            <br>
                            {{ form.email.errors }}
                            {{ form.non_field_errors }}
                        </div>
                    </div>
                </form>
            </article>
        </div>
        <p class="register-no-account">Have an account?</p>
        <p class="signin">
            <a class="btn" href="{% url 'signin' %}">SIGN IN HERE</a>
        </p>
    </section>
{% endblock %}